### ISSUE TITLE
Is er een goede reden de requestBody van historieberichten met polymorphy in te richten?

### ISSUE THREAD

**Issue by melsk-r** [BRP-API/Haal-Centraal-BRP-historie-bevragen#59]
De requestBody van de 4 berichten in mijn voorstel voor de 2.0.0 versie van de BRP historie bevragen specificatie ziet er nu als volgt uit:

```
    HistorieQuery:
      required:
      - burgerservicenummer
      - fields
      type: object
      properties:
        burgerservicenummer:
          maxItems: 20
          minItems: 1
          type: array
          items:
            $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/develop/specificatie/persoon.yaml#/components/schemas/Burgerservicenummer"
        fields:
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/develop/specificatie/filter.yaml#/components/schemas/Fields"
        peildatum:
          type: string
          description: |
            De datum waarop de resource wordt opgevraagd.
          format: date
          example: 1964-09-24
        datumVan:
          type: string
          description: |
            De begindatum van de periode waarover de resource wordt opgevraagd.
          format: date
          example: 1964-09-24
        datumTotEnMet:
          type: string
          description: |
            De einddatum van de periode waarover de resource wordt opgevraagd.
          format: date
          example: 1964-09-24
```
met de volgende omschrijving:

> Zoek de xxxxxxxhistorie van een persoon op de opgegeven peildatum of binnen de opgegeven periode. Als je geen peildatum of periode opgeeft, krijg je alle xxxxxxx van de persoon terug. De meest actuele xxxxxxx staat bovenaan.

Je zou op basis daarvan polymorphy kunnen introduceren waarmee je n.m.m. de volgende versies van de requestBody kunt creëren:
1. Een versie waarin peildatum verplicht is en datumVan en datumTot ontbreken;
2. Een versie waarin datumVan en datumTot verplicht zijn en peildatum ontbreekt;
3. Een versie waarin datumVan verplicht is en datumTot en peildatum ontbreken;
4. Een versie waarin datumTot verplicht is en datumVan en peildatum ontbreken;
5. Een versie waarin zowel peildatum als datumVan en datumTot ontbreken.

De vraag is of alle bovenstaande varianten wel noodzakelijk zijn. Met name de laatste 3 varianten kun je ook met variant 2 invullen als je de afspraak maakt dat bij:
'3' datumTot de huidige datum is.
'4' datumVan een waarde heeft die kleiner is dan de geboortedatum van een persoon.
'5' datumVan een waarde heeft die kleiner is dan de geboortedatum van een persoon en datumTot de huidige datum is.

met als gevolg dat je afdwingt dat er een bewuste keuze wordt gemaakt.

Ik vraag me nog wel af of het voordeel dat je bereikt met de introductie van polymorphy op deze plaats wel opweegt tegen een complexere structuur.
